[package]
name = "ccs-vp"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.22.0"

[dependencies]
itertools = "0.14.0"
lalrpop-util = { version = "0.22.0", features = ["lexer"] }
ccs = { path = "../ccs" }
